# Generated by Django 5.0.3 on 2024-08-24 13:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('data', models.DateField(verbose_name='Data')),
                ('image_front', models.ImageField(upload_to='blog/', verbose_name='image front')),
                ('description_front', models.TextField(verbose_name='description front')),
                ('description_front_en', models.TextField(null=True, verbose_name='description front')),
                ('description_front_ru', models.TextField(null=True, verbose_name='description front')),
                ('description_front_uz', models.TextField(null=True, verbose_name='description front')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='image back')),
                ('description_uz', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description uz')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description ru')),
                ('description_eng', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description eng')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('description_en', models.CharField(max_length=256, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=256, null=True, verbose_name='Description')),
                ('description_uz', models.CharField(max_length=256, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('type_en', models.CharField(max_length=255, null=True, verbose_name='type')),
                ('type_ru', models.CharField(max_length=255, null=True, verbose_name='type')),
                ('type_uz', models.CharField(max_length=255, null=True, verbose_name='type')),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='project_image_logo/', verbose_name='image_logo')),
                ('description_short', models.TextField(verbose_name='description_short')),
                ('description_short_en', models.TextField(null=True, verbose_name='description_short')),
                ('description_short_ru', models.TextField(null=True, verbose_name='description_short')),
                ('description_short_uz', models.TextField(null=True, verbose_name='description_short')),
                ('project_type', models.CharField(max_length=255, verbose_name='project_type')),
                ('project_type_en', models.CharField(max_length=255, null=True, verbose_name='project_type')),
                ('project_type_ru', models.CharField(max_length=255, null=True, verbose_name='project_type')),
                ('project_type_uz', models.CharField(max_length=255, null=True, verbose_name='project_type')),
                ('preview', models.CharField(max_length=255, verbose_name='preview')),
                ('preview_en', models.CharField(max_length=255, null=True, verbose_name='preview')),
                ('preview_ru', models.CharField(max_length=255, null=True, verbose_name='preview')),
                ('preview_uz', models.CharField(max_length=255, null=True, verbose_name='preview')),
                ('description_long', models.TextField(verbose_name='description_long')),
                ('description_long_en', models.TextField(null=True, verbose_name='description_long')),
                ('description_long_ru', models.TextField(null=True, verbose_name='description_long')),
                ('description_long_uz', models.TextField(null=True, verbose_name='description_long')),
                ('video', models.FileField(blank=True, null=True, upload_to='project_video/', verbose_name='video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/', verbose_name='image')),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube_link')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Full name')),
                ('image', models.ImageField(upload_to='team/', verbose_name='image')),
                ('position', models.CharField(max_length=256, verbose_name='Position')),
                ('position_en', models.CharField(max_length=256, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=256, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=256, null=True, verbose_name='Position')),
                ('linkedin_link', models.CharField(max_length=256, verbose_name='Linkedin link')),
                ('team_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.team_category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
