# Generated by Django 5.0.3 on 2024-08-29 11:47

import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('banner', models.ImageField(upload_to='blog/')),
                ('description_short', models.TextField()),
                ('description_short_en', models.TextField(null=True)),
                ('description_short_ru', models.TextField(null=True)),
                ('description_short_uz', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Team Category',
                'verbose_name_plural': 'Team Categories',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('type_en', models.CharField(max_length=255, null=True)),
                ('type_ru', models.CharField(max_length=255, null=True)),
                ('type_uz', models.CharField(max_length=255, null=True)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='project_image_logo/')),
                ('description_short', models.TextField()),
                ('description_short_en', models.TextField(null=True)),
                ('description_short_ru', models.TextField(null=True)),
                ('description_short_uz', models.TextField(null=True)),
                ('project_type', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='project_video/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/')),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('full_name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='team/')),
                ('linkedin', models.URLField(max_length=256, validators=[company.models.validate_linkedin_url])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='company.teamcategory')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.teamposition')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
