# Generated by Django 5.0.3 on 2024-08-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_short_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_short_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_short_uz',
        ),
    ]
