# Generated by Django 5.0.3 on 2024-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title_en',
            new_name='project_type_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_ru',
            new_name='project_type_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_uz',
            new_name='project_type_uz',
        ),
        migrations.AddField(
            model_name='project',
            name='description_long_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_long_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_long_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.CharField(max_length=255, verbose_name='Previw Link'),
        ),
    ]
