# Generated by Django 5.0.3 on 2024-08-30 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_title_en_project_project_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
