# Generated by Django 5.0.3 on 2024-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_blog_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
